[package]
name = "_3_2"
version = "0.1.0"
authors = ["Marcel Schramm <marceloschr@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
